apiVersion: v1
kind: Namespace
metadata:
  name: ns-a-service

---

apiVersion: v1
kind: Service
metadata:
  name: servicea
  namespace: ns-a-service
spec:
  selector:
    app: servicea
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  namespace: ns-a-service
spec:
  selector:
    matchLabels:
      app: servicea
  replicas: 2
  template:
    metadata:
      namespace: ns-a-service
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: aadir/service_a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ready  
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 60